### ISSUE TITLE
Magisk刷入1.40.02版本的模块后emoji显示为黑白

### ISSUE THREAD

**Issue by Panda35064** [ozingi/winemoji-magisk#1]
![Screenshot_20230725-212422_信息](https://github.com/ozingi/winemoji-magisk/assets/113248487/8e0b991c-6bde-4492-9820-c390ada30486)
Android版本为12.1，系统为PE Plus
Magisk版本为f95478f1-alpha

**Comment by ozingi** [comment]
你的系统字体是不是改过？

**Comment by Panda35064** [comment]
是的没错，用字体模块改的

**Comment by ozingi** [comment]
把其他字体模块卸载就行了
